/*
 * This source file was generated by the Gradle 'init' task
 */
package tuner;

import java.awt.Color;
import java.awt.Graphics;

import javax.swing.JFrame;
import javax.swing.JPanel;

class CurvePanel extends JPanel {
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Draw the background
        g.setColor(Color.WHITE);
        g.fillRect(40, 50, 700, 400);
        // Draw the border
        g.setColor(Color.BLACK);
        g.drawRect(40, 50, 700, 400);
        // Draw the line
        g.setColor(Color.RED);
        g.drawLine(40, 450, 740, 50);
    }
}

public class App {
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setSize(800, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.add(new CurvePanel());

        frame.setVisible(true);
    }
}
